updated intelpython3_full dockerfile
IntelPython/container-images pull request #31
Opened 2023-05-24 18:24 UTC by devpramod-intel

The current intelpython3_dockerfile is outdated. The updated dockerfile pulls the latest image from miniconda and installs the latest available version of intelpython3_full

2023-05-25 13:11 UTC, xaleryb commented
@aguzmanballen  could you please have a look if this change is good enough or there is something more we need to do?

2023-05-25 14:01 UTC, AndresGuzman-Ballen requested changes
Thanks for creating the PR! Would you be able to take a look at the one comment I made?

2023-05-31 17:05 UTC, devpramod-intel commented on configs/intelpython3_full/Dockerfile
> +RUN conda install  -y -q intelpython3_full
@AndresGuzman-Ballen Thank you! I have made the change

2023-05-31 17:25 UTC, AndresGuzman-Ballen commented on configs/intelpython3_full/Dockerfile
> +RUN conda install  -y -q intelpython3_full
@devpramod-intel thank you!

2023-05-31 18:59 UTC, merged